#!/bin/bash
# Bash script to ingest data
# This involves scraping the data from the web and then cleaning up and putting in Weaviate.
# Error if any command fails
set -o errexit
set -o pipefail
set -o nounset
echo "entrpoint"
python3 ingest.py
